package com.reportmanage.model;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.classnum
     *
     * @mbggenerated
     */
    private String classnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.classname
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Class.studentcount
     *
     * @mbggenerated
     */
    private String studentcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.id
     *
     * @return the value of Class.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.id
     *
     * @param id the value for Class.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.classnum
     *
     * @return the value of Class.classnum
     *
     * @mbggenerated
     */
    public String getClassnum() {
        return classnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.classnum
     *
     * @param classnum the value for Class.classnum
     *
     * @mbggenerated
     */
    public void setClassnum(String classnum) {
        this.classnum = classnum == null ? null : classnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.classname
     *
     * @return the value of Class.classname
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.classname
     *
     * @param classname the value for Class.classname
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Class.studentcount
     *
     * @return the value of Class.studentcount
     *
     * @mbggenerated
     */
    public String getStudentcount() {
        return studentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Class.studentcount
     *
     * @param studentcount the value for Class.studentcount
     *
     * @mbggenerated
     */
    public void setStudentcount(String studentcount) {
        this.studentcount = studentcount == null ? null : studentcount.trim();
    }
}