package com.reportmanage.model;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File.filetype
     *
     * @mbggenerated
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File.filepath
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File.id
     *
     * @return the value of File.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File.id
     *
     * @param id the value for File.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File.filename
     *
     * @return the value of File.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File.filename
     *
     * @param filename the value for File.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File.filetype
     *
     * @return the value of File.filetype
     *
     * @mbggenerated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File.filetype
     *
     * @param filetype the value for File.filetype
     *
     * @mbggenerated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File.filepath
     *
     * @return the value of File.filepath
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File.filepath
     *
     * @param filepath the value for File.filepath
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }
}