package com.reportmanage.model;

import java.util.Date;

public class Progress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Progress.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Progress.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Progress.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Progress.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Progress.missionid
     *
     * @mbggenerated
     */
    private Integer missionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Progress.id
     *
     * @return the value of Progress.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Progress.id
     *
     * @param id the value for Progress.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Progress.userid
     *
     * @return the value of Progress.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Progress.userid
     *
     * @param userid the value for Progress.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Progress.createtime
     *
     * @return the value of Progress.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Progress.createtime
     *
     * @param createtime the value for Progress.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Progress.description
     *
     * @return the value of Progress.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Progress.description
     *
     * @param description the value for Progress.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Progress.missionid
     *
     * @return the value of Progress.missionid
     *
     * @mbggenerated
     */
    public Integer getMissionid() {
        return missionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Progress.missionid
     *
     * @param missionid the value for Progress.missionid
     *
     * @mbggenerated
     */
    public void setMissionid(Integer missionid) {
        this.missionid = missionid;
    }
}