package com.reportmanage.dao;

import com.reportmanage.model.Commit;

import java.util.List;

public interface CommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    int insert(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    int insertSelective(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    Commit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Commit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commit record);

    List<Commit> selectByMissionId(int i);

    Commit selectByUserId(int i);
}