package com.reportmanage.dao;

import com.reportmanage.model.Guidebook;
import com.reportmanage.model.Mission;

import java.util.List;

public interface GuidebookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    int insert(Guidebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    int insertSelective(Guidebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    Guidebook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Guidebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GuideBook
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Guidebook record);

    List<Guidebook> selectByUserId(int i);

    Guidebook selectByUserIdThoughtClass(int i);
}