package com.reportmanage.dao;

import com.reportmanage.model.Progress;

import java.util.List;

public interface ProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    int insert(Progress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    int insertSelective(Progress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    Progress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Progress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Progress record);

    List<Progress> selectByUserid(Integer id);
}