package com.reportmanage.dao;

import com.reportmanage.model.Guidebook;
import com.reportmanage.model.Require;

import java.util.List;

public interface RequireMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    int insert(Require record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    int insertSelective(Require record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    Require selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Require record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Require
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Require record);

    List<Require> selectByUserId(int i);

    Require selectByUserIdThoughtClass(int i);
}